// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/samsahai/rpc/service.proto

package rpc

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ComponentUpgrade_UpgradeStatus int32

const (
	ComponentUpgrade_UpgradeStatus_FAILURE ComponentUpgrade_UpgradeStatus = 0
	ComponentUpgrade_UpgradeStatus_SUCCESS ComponentUpgrade_UpgradeStatus = 1
)

var ComponentUpgrade_UpgradeStatus_name = map[int32]string{
	0: "UpgradeStatus_FAILURE",
	1: "UpgradeStatus_SUCCESS",
}

var ComponentUpgrade_UpgradeStatus_value = map[string]int32{
	"UpgradeStatus_FAILURE": 0,
	"UpgradeStatus_SUCCESS": 1,
}

func (x ComponentUpgrade_UpgradeStatus) String() string {
	return proto.EnumName(ComponentUpgrade_UpgradeStatus_name, int32(x))
}

func (ComponentUpgrade_UpgradeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{3, 0}
}

type ComponentUpgrade_IssueType int32

const (
	ComponentUpgrade_IssueType_UNKNOWN                ComponentUpgrade_IssueType = 0
	ComponentUpgrade_IssueType_DESIRED_VERSION_FAILED ComponentUpgrade_IssueType = 1
	ComponentUpgrade_IssueType_IMAGE_MISSING          ComponentUpgrade_IssueType = 2
	ComponentUpgrade_IssueType_ENVIRONMENT_ISSUE      ComponentUpgrade_IssueType = 3
)

var ComponentUpgrade_IssueType_name = map[int32]string{
	0: "IssueType_UNKNOWN",
	1: "IssueType_DESIRED_VERSION_FAILED",
	2: "IssueType_IMAGE_MISSING",
	3: "IssueType_ENVIRONMENT_ISSUE",
}

var ComponentUpgrade_IssueType_value = map[string]int32{
	"IssueType_UNKNOWN":                0,
	"IssueType_DESIRED_VERSION_FAILED": 1,
	"IssueType_IMAGE_MISSING":          2,
	"IssueType_ENVIRONMENT_ISSUE":      3,
}

func (x ComponentUpgrade_IssueType) String() string {
	return proto.EnumName(ComponentUpgrade_IssueType_name, int32(x))
}

func (ComponentUpgrade_IssueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{3, 1}
}

type ComponentUpgrade_ReverificationStatus int32

const (
	ComponentUpgrade_ReverificationStatus_UNKNOWN ComponentUpgrade_ReverificationStatus = 0
	ComponentUpgrade_ReverificationStatus_FAILURE ComponentUpgrade_ReverificationStatus = 1
	ComponentUpgrade_ReverificationStatus_SUCCESS ComponentUpgrade_ReverificationStatus = 2
)

var ComponentUpgrade_ReverificationStatus_name = map[int32]string{
	0: "ReverificationStatus_UNKNOWN",
	1: "ReverificationStatus_FAILURE",
	2: "ReverificationStatus_SUCCESS",
}

var ComponentUpgrade_ReverificationStatus_value = map[string]int32{
	"ReverificationStatus_UNKNOWN": 0,
	"ReverificationStatus_FAILURE": 1,
	"ReverificationStatus_SUCCESS": 2,
}

func (x ComponentUpgrade_ReverificationStatus) String() string {
	return proto.EnumName(ComponentUpgrade_ReverificationStatus_name, int32(x))
}

func (ComponentUpgrade_ReverificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{3, 2}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Team struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{1}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Configuration struct {
	Config               []byte   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	GitRevision          string   `protobuf:"bytes,2,opt,name=gitRevision,proto3" json:"gitRevision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{2}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Configuration) GetGitRevision() string {
	if m != nil {
		return m.GitRevision
	}
	return ""
}

type ComponentUpgrade struct {
	Status               ComponentUpgrade_UpgradeStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=samsahai.io.samsahai.ComponentUpgrade_UpgradeStatus" json:"status,omitempty"`
	Name                 string                                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TeamName             string                                `protobuf:"bytes,3,opt,name=teamName,proto3" json:"teamName,omitempty"`
	Image                *Image                                `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	IssueType            ComponentUpgrade_IssueType            `protobuf:"varint,5,opt,name=issueType,proto3,enum=samsahai.io.samsahai.ComponentUpgrade_IssueType" json:"issueType,omitempty"`
	QueueHistoryName     string                                `protobuf:"bytes,6,opt,name=queueHistoryName,proto3" json:"queueHistoryName,omitempty"`
	ImageMissingList     []*Image                              `protobuf:"bytes,7,rep,name=imageMissingList,proto3" json:"imageMissingList,omitempty"`
	Namespace            string                                `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TestBuildTypeID      string                                `protobuf:"bytes,9,opt,name=testBuildTypeID,proto3" json:"testBuildTypeID,omitempty"`
	Runs                 int32                                 `protobuf:"varint,10,opt,name=runs,proto3" json:"runs,omitempty"`
	IsReverify           bool                                  `protobuf:"varint,11,opt,name=isReverify,proto3" json:"isReverify,omitempty"`
	ReverificationStatus ComponentUpgrade_ReverificationStatus `protobuf:"varint,12,opt,name=reverificationStatus,proto3,enum=samsahai.io.samsahai.ComponentUpgrade_ReverificationStatus" json:"reverificationStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ComponentUpgrade) Reset()         { *m = ComponentUpgrade{} }
func (m *ComponentUpgrade) String() string { return proto.CompactTextString(m) }
func (*ComponentUpgrade) ProtoMessage()    {}
func (*ComponentUpgrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{3}
}

func (m *ComponentUpgrade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentUpgrade.Unmarshal(m, b)
}
func (m *ComponentUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentUpgrade.Marshal(b, m, deterministic)
}
func (m *ComponentUpgrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentUpgrade.Merge(m, src)
}
func (m *ComponentUpgrade) XXX_Size() int {
	return xxx_messageInfo_ComponentUpgrade.Size(m)
}
func (m *ComponentUpgrade) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentUpgrade.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentUpgrade proto.InternalMessageInfo

func (m *ComponentUpgrade) GetStatus() ComponentUpgrade_UpgradeStatus {
	if m != nil {
		return m.Status
	}
	return ComponentUpgrade_UpgradeStatus_FAILURE
}

func (m *ComponentUpgrade) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComponentUpgrade) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *ComponentUpgrade) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ComponentUpgrade) GetIssueType() ComponentUpgrade_IssueType {
	if m != nil {
		return m.IssueType
	}
	return ComponentUpgrade_IssueType_UNKNOWN
}

func (m *ComponentUpgrade) GetQueueHistoryName() string {
	if m != nil {
		return m.QueueHistoryName
	}
	return ""
}

func (m *ComponentUpgrade) GetImageMissingList() []*Image {
	if m != nil {
		return m.ImageMissingList
	}
	return nil
}

func (m *ComponentUpgrade) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ComponentUpgrade) GetTestBuildTypeID() string {
	if m != nil {
		return m.TestBuildTypeID
	}
	return ""
}

func (m *ComponentUpgrade) GetRuns() int32 {
	if m != nil {
		return m.Runs
	}
	return 0
}

func (m *ComponentUpgrade) GetIsReverify() bool {
	if m != nil {
		return m.IsReverify
	}
	return false
}

func (m *ComponentUpgrade) GetReverificationStatus() ComponentUpgrade_ReverificationStatus {
	if m != nil {
		return m.ReverificationStatus
	}
	return ComponentUpgrade_ReverificationStatus_UNKNOWN
}

type Image struct {
	Repository           string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{4}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Image) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ImageList struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageList) Reset()         { *m = ImageList{} }
func (m *ImageList) String() string { return proto.CompactTextString(m) }
func (*ImageList) ProtoMessage()    {}
func (*ImageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{5}
}

func (m *ImageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageList.Unmarshal(m, b)
}
func (m *ImageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageList.Marshal(b, m, deterministic)
}
func (m *ImageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageList.Merge(m, src)
}
func (m *ImageList) XXX_Size() int {
	return xxx_messageInfo_ImageList.Size(m)
}
func (m *ImageList) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageList.DiscardUnknown(m)
}

var xxx_messageInfo_ImageList proto.InternalMessageInfo

func (m *ImageList) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type TeamWithCurrentComponent struct {
	TeamName             string   `protobuf:"bytes,1,opt,name=teamName,proto3" json:"teamName,omitempty"`
	CompName             string   `protobuf:"bytes,2,opt,name=compName,proto3" json:"compName,omitempty"`
	Image                *Image   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamWithCurrentComponent) Reset()         { *m = TeamWithCurrentComponent{} }
func (m *TeamWithCurrentComponent) String() string { return proto.CompactTextString(m) }
func (*TeamWithCurrentComponent) ProtoMessage()    {}
func (*TeamWithCurrentComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb42a50bcb57dea2, []int{6}
}

func (m *TeamWithCurrentComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamWithCurrentComponent.Unmarshal(m, b)
}
func (m *TeamWithCurrentComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamWithCurrentComponent.Marshal(b, m, deterministic)
}
func (m *TeamWithCurrentComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamWithCurrentComponent.Merge(m, src)
}
func (m *TeamWithCurrentComponent) XXX_Size() int {
	return xxx_messageInfo_TeamWithCurrentComponent.Size(m)
}
func (m *TeamWithCurrentComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamWithCurrentComponent.DiscardUnknown(m)
}

var xxx_messageInfo_TeamWithCurrentComponent proto.InternalMessageInfo

func (m *TeamWithCurrentComponent) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *TeamWithCurrentComponent) GetCompName() string {
	if m != nil {
		return m.CompName
	}
	return ""
}

func (m *TeamWithCurrentComponent) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func init() {
	proto.RegisterEnum("samsahai.io.samsahai.ComponentUpgrade_UpgradeStatus", ComponentUpgrade_UpgradeStatus_name, ComponentUpgrade_UpgradeStatus_value)
	proto.RegisterEnum("samsahai.io.samsahai.ComponentUpgrade_IssueType", ComponentUpgrade_IssueType_name, ComponentUpgrade_IssueType_value)
	proto.RegisterEnum("samsahai.io.samsahai.ComponentUpgrade_ReverificationStatus", ComponentUpgrade_ReverificationStatus_name, ComponentUpgrade_ReverificationStatus_value)
	proto.RegisterType((*Empty)(nil), "samsahai.io.samsahai.Empty")
	proto.RegisterType((*Team)(nil), "samsahai.io.samsahai.Team")
	proto.RegisterType((*Configuration)(nil), "samsahai.io.samsahai.Configuration")
	proto.RegisterType((*ComponentUpgrade)(nil), "samsahai.io.samsahai.ComponentUpgrade")
	proto.RegisterType((*Image)(nil), "samsahai.io.samsahai.Image")
	proto.RegisterType((*ImageList)(nil), "samsahai.io.samsahai.ImageList")
	proto.RegisterType((*TeamWithCurrentComponent)(nil), "samsahai.io.samsahai.TeamWithCurrentComponent")
}

func init() { proto.RegisterFile("pkg/samsahai/rpc/service.proto", fileDescriptor_bb42a50bcb57dea2) }

var fileDescriptor_bb42a50bcb57dea2 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xc6, 0x09, 0x09, 0xc9, 0x00, 0xe7, 0x98, 0x15, 0x1c, 0x7c, 0x02, 0x02, 0xcb, 0xad, 0xaa,
	0xa8, 0x17, 0xa1, 0x85, 0xde, 0x54, 0xbd, 0x29, 0x24, 0x6e, 0x6a, 0x95, 0x18, 0xb4, 0x26, 0x20,
	0xf5, 0xa2, 0x91, 0x6b, 0x16, 0xb3, 0x6a, 0xfd, 0xd3, 0xdd, 0x35, 0x52, 0xa4, 0xde, 0xb6, 0xcf,
	0xd1, 0x77, 0xe9, 0x8b, 0x55, 0x5e, 0x9c, 0x38, 0x21, 0x4e, 0xc9, 0x55, 0x66, 0x3f, 0xcf, 0xcc,
	0x7e, 0x33, 0x3b, 0xf3, 0x05, 0xf6, 0xe2, 0x2f, 0xfe, 0x01, 0x77, 0x03, 0xee, 0xde, 0xba, 0xf4,
	0x80, 0xc5, 0xde, 0x01, 0x27, 0xec, 0x8e, 0x7a, 0xa4, 0x15, 0xb3, 0x48, 0x44, 0x68, 0x73, 0xf4,
	0xad, 0x45, 0xa3, 0xd6, 0xc8, 0x36, 0x56, 0xa0, 0x62, 0x06, 0xb1, 0x18, 0x1a, 0x0d, 0x58, 0xbe,
	0x20, 0x6e, 0x80, 0x10, 0x2c, 0x87, 0x6e, 0x40, 0x34, 0x45, 0x57, 0x9a, 0x75, 0x2c, 0x6d, 0xc3,
	0x82, 0xf5, 0x76, 0x14, 0xde, 0x50, 0x3f, 0x61, 0xae, 0xa0, 0x51, 0x88, 0xfe, 0x83, 0xaa, 0x27,
	0x01, 0xe9, 0xb6, 0x86, 0xb3, 0x13, 0xd2, 0x61, 0xd5, 0xa7, 0x02, 0x93, 0x3b, 0xca, 0x69, 0x14,
	0x6a, 0x25, 0x99, 0x63, 0x12, 0x32, 0x7e, 0xaf, 0x80, 0xda, 0x8e, 0x82, 0x38, 0x0a, 0x49, 0x28,
	0xfa, 0xb1, 0xcf, 0xdc, 0x6b, 0x82, 0x4e, 0xa1, 0xca, 0x85, 0x2b, 0x12, 0x2e, 0xd3, 0xfd, 0x73,
	0xf8, 0xaa, 0x55, 0xc4, 0xb5, 0xf5, 0x30, 0xae, 0x95, 0xfd, 0x3a, 0x32, 0x16, 0x67, 0x39, 0xc6,
	0x15, 0x94, 0xf2, 0x0a, 0x50, 0x03, 0x6a, 0x82, 0xb8, 0x81, 0x9d, 0xe2, 0x65, 0x89, 0x8f, 0xcf,
	0xe8, 0x25, 0x54, 0x68, 0xe0, 0xfa, 0x44, 0x5b, 0xd6, 0x95, 0xe6, 0xea, 0xe1, 0x4e, 0xf1, 0xe5,
	0x56, 0xea, 0x82, 0xef, 0x3d, 0x91, 0x0d, 0x75, 0xca, 0x79, 0x42, 0x2e, 0x86, 0x31, 0xd1, 0x2a,
	0x92, 0xf3, 0x8b, 0x05, 0x39, 0x5b, 0xa3, 0x38, 0x9c, 0xa7, 0x40, 0xcf, 0x41, 0xfd, 0x96, 0x90,
	0x84, 0xbc, 0xa7, 0x5c, 0x44, 0x6c, 0x28, 0x69, 0x56, 0x25, 0xcd, 0x19, 0x1c, 0x75, 0x41, 0x95,
	0x24, 0x7a, 0x94, 0x73, 0x1a, 0xfa, 0xa7, 0x94, 0x0b, 0x6d, 0x45, 0x2f, 0x3f, 0xc6, 0x7c, 0x26,
	0x08, 0xed, 0x42, 0x3d, 0xed, 0x0d, 0x8f, 0x5d, 0x8f, 0x68, 0x35, 0x79, 0x5b, 0x0e, 0xa0, 0x26,
	0xfc, 0x2b, 0x08, 0x17, 0x27, 0x09, 0xfd, 0x7a, 0x9d, 0x72, 0xb4, 0x3a, 0x5a, 0x5d, 0xfa, 0x3c,
	0x84, 0xd3, 0x7e, 0xb3, 0x24, 0xe4, 0x1a, 0xe8, 0x4a, 0xb3, 0x82, 0xa5, 0x8d, 0xf6, 0x00, 0x28,
	0xc7, 0xe4, 0x8e, 0x30, 0x7a, 0x33, 0xd4, 0x56, 0x75, 0xa5, 0x59, 0xc3, 0x13, 0x08, 0x8a, 0x60,
	0x93, 0xdd, 0xdb, 0xd4, 0x93, 0x23, 0x75, 0xff, 0x86, 0xda, 0x9a, 0xec, 0xe5, 0x9b, 0x05, 0x7b,
	0x89, 0x0b, 0x52, 0xe0, 0xc2, 0xc4, 0x86, 0x09, 0xeb, 0x53, 0xd3, 0x82, 0xfe, 0x87, 0xad, 0x29,
	0x60, 0xf0, 0xee, 0xd8, 0x3a, 0xed, 0x63, 0x53, 0x5d, 0x9a, 0xfd, 0xe4, 0xf4, 0xdb, 0x6d, 0xd3,
	0x71, 0x54, 0xc5, 0xf8, 0xa9, 0x40, 0x7d, 0xfc, 0x82, 0x68, 0x0b, 0x36, 0xc6, 0x87, 0x41, 0xdf,
	0xfe, 0x60, 0x9f, 0x5d, 0xd9, 0xea, 0x12, 0x7a, 0x0a, 0x7a, 0x0e, 0x77, 0x4c, 0xc7, 0xc2, 0x66,
	0x67, 0x70, 0x69, 0x62, 0xc7, 0x3a, 0xb3, 0xe5, 0x35, 0x66, 0x47, 0x55, 0xd0, 0x0e, 0x6c, 0xe7,
	0x5e, 0x56, 0xef, 0xb8, 0x6b, 0x0e, 0x7a, 0x96, 0xe3, 0x58, 0x76, 0x57, 0x2d, 0xa1, 0x7d, 0xd8,
	0xc9, 0x3f, 0x9a, 0xf6, 0xa5, 0x85, 0xcf, 0xec, 0x9e, 0x69, 0x5f, 0x0c, 0x2c, 0xc7, 0xe9, 0x9b,
	0x6a, 0xd9, 0xf8, 0x0e, 0x9b, 0x45, 0xd5, 0x23, 0x1d, 0x76, 0x8b, 0xf0, 0x09, 0x76, 0xf3, 0x3c,
	0x46, 0xf5, 0x2b, 0x73, 0x3d, 0x46, 0x6d, 0x28, 0x19, 0xaf, 0xa1, 0x22, 0xa7, 0x2a, 0x7d, 0x67,
	0x46, 0xe2, 0x88, 0xd3, 0x74, 0x3c, 0x33, 0xcd, 0x98, 0x40, 0x90, 0x0a, 0x65, 0xe1, 0xfa, 0xd9,
	0x2a, 0xa6, 0xa6, 0xf1, 0x16, 0xea, 0x32, 0x54, 0x8e, 0xe0, 0x11, 0x54, 0xe5, 0x58, 0xa6, 0x8b,
	0xff, 0xe8, 0x04, 0x67, 0xae, 0xc6, 0x0f, 0x05, 0xb4, 0x54, 0xaa, 0xae, 0xa8, 0xb8, 0x6d, 0x27,
	0x8c, 0x91, 0x50, 0x8c, 0x27, 0x63, 0x6a, 0xd1, 0x95, 0x07, 0x8b, 0xde, 0x80, 0x9a, 0x17, 0x05,
	0xb1, 0x9d, 0x8b, 0xc3, 0xf8, 0x9c, 0x8b, 0x40, 0x79, 0x51, 0x11, 0x38, 0xfc, 0x55, 0x82, 0x32,
	0x3e, 0x6f, 0x23, 0x07, 0xd4, 0x2e, 0x11, 0xd3, 0x02, 0xd9, 0x28, 0x8e, 0x4f, 0x69, 0x37, 0x9e,
	0xcc, 0x9b, 0xee, 0xc9, 0x04, 0x9f, 0x60, 0x1b, 0x27, 0xe1, 0x79, 0xc4, 0xc5, 0x8c, 0x5a, 0x3e,
	0x5b, 0x6c, 0x3b, 0x1a, 0x73, 0x6a, 0x90, 0x72, 0x8f, 0xae, 0x61, 0xa3, 0x4b, 0x44, 0x26, 0x07,
	0x97, 0x84, 0xa5, 0xe2, 0x8c, 0x5a, 0xf3, 0x59, 0x17, 0x35, 0xbb, 0xb1, 0xff, 0x97, 0x2e, 0xa5,
	0xef, 0x7b, 0x52, 0xf9, 0x58, 0x66, 0xb1, 0xf7, 0xb9, 0x2a, 0xff, 0x81, 0x8e, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x83, 0x7f, 0x79, 0x1f, 0xa3, 0x06, 0x00, 0x00,
}
