coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "**/zz_generated*.go"
  - "**/*.pb.go"
  - "**/*.twirp.go"