apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "samsahai.fullname" . }}
  labels:
    {{ include "samsahai.labels" . | indent 4 | trim }}
rules:
  - apiGroups:
      - env.samsahai.io
    resources:
      - teams
      - activepromotions
      - activepromotionhistories
      - configs
      - desiredcomponents
      - queues
      - queuehistories
      - stablecomponents
    verbs:
      - "*"
  - apiGroups:
      - flux.weave.works
    resources:
      - helmreleases
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - bindings
      - configmaps
      - limitranges
      - persistentvolumeclaims
      - pods
      - pods/log
      - namespaces
      - resourcequotas
      - services
      - serviceaccounts
      - secrets
      - replicationcontrollers
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - deployments
      - statefulsets
      - replicasets
      - ingresses
      - networkpolicies
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "samsahai.fullname" . }}
  labels:
    {{ include "samsahai.labels" . | indent 4 | trim }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "samsahai.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "samsahai.fullname" . }}
    namespace: {{ .Release.Namespace }}