// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/staging/rpc/service.proto

package rpc

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3896b0de76041e06, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Configuration struct {
	Config               []byte   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	GitRevision          string   `protobuf:"bytes,2,opt,name=gitRevision,proto3" json:"gitRevision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_3896b0de76041e06, []int{1}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Configuration) GetGitRevision() string {
	if m != nil {
		return m.GitRevision
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "samsahai.io.staging.Empty")
	proto.RegisterType((*Configuration)(nil), "samsahai.io.staging.Configuration")
}

func init() { proto.RegisterFile("pkg/staging/rpc/service.proto", fileDescriptor_3896b0de76041e06) }

var fileDescriptor_3896b0de76041e06 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xc8, 0x4e, 0xd7,
	0x2f, 0x2e, 0x49, 0x4c, 0xcf, 0xcc, 0x4b, 0xd7, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0x4e, 0xcc, 0x2d, 0x4e,
	0xcc, 0x48, 0xcc, 0xd4, 0xcb, 0xcc, 0xd7, 0x83, 0x2a, 0x53, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d,
	0x28, 0xa9, 0x54, 0xf2, 0xe4, 0xe2, 0x75, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x2f, 0x2d, 0x4a, 0x2c,
	0xc9, 0xcc, 0xcf, 0x13, 0x12, 0xe3, 0x62, 0x4b, 0x06, 0x0b, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0,
	0x04, 0x41, 0x79, 0x42, 0x0a, 0x5c, 0xdc, 0xe9, 0x99, 0x25, 0x41, 0xa9, 0x65, 0x99, 0xc5, 0x99,
	0xf9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xc8, 0x42, 0x46, 0x31, 0x5c, 0xcc, 0x41,
	0x01, 0xce, 0x42, 0xa1, 0x5c, 0xc2, 0xa1, 0x05, 0x29, 0x89, 0x25, 0xa9, 0xa8, 0xe6, 0x2a, 0xe9,
	0x61, 0x71, 0x87, 0x1e, 0x8a, 0x1a, 0x29, 0x29, 0xac, 0x6a, 0xc0, 0x0e, 0x75, 0x62, 0x8d, 0x62,
	0x2e, 0x2a, 0x48, 0x4e, 0x62, 0x03, 0x7b, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x3e,
	0xfe, 0x84, 0xf5, 0x00, 0x00, 0x00,
}
