// +build !ignore_autogenerated

/*
Copyright 2019 Agoda DevOps Container.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotion) DeepCopyInto(out *ActivePromotion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotion.
func (in *ActivePromotion) DeepCopy() *ActivePromotion {
	if in == nil {
		return nil
	}
	out := new(ActivePromotion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivePromotion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionCondition) DeepCopyInto(out *ActivePromotionCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionCondition.
func (in *ActivePromotionCondition) DeepCopy() *ActivePromotionCondition {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionHistory) DeepCopyInto(out *ActivePromotionHistory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionHistory.
func (in *ActivePromotionHistory) DeepCopy() *ActivePromotionHistory {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivePromotionHistory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ActivePromotionHistoryByCreatedTimeDESC) DeepCopyInto(out *ActivePromotionHistoryByCreatedTimeDESC) {
	{
		in := &in
		*out = make(ActivePromotionHistoryByCreatedTimeDESC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionHistoryByCreatedTimeDESC.
func (in ActivePromotionHistoryByCreatedTimeDESC) DeepCopy() ActivePromotionHistoryByCreatedTimeDESC {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionHistoryByCreatedTimeDESC)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionHistoryList) DeepCopyInto(out *ActivePromotionHistoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActivePromotionHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionHistoryList.
func (in *ActivePromotionHistoryList) DeepCopy() *ActivePromotionHistoryList {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionHistoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivePromotionHistoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionHistorySpec) DeepCopyInto(out *ActivePromotionHistorySpec) {
	*out = *in
	if in.ActivePromotion != nil {
		in, out := &in.ActivePromotion, &out.ActivePromotion
		*out = new(ActivePromotion)
		(*in).DeepCopyInto(*out)
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionHistorySpec.
func (in *ActivePromotionHistorySpec) DeepCopy() *ActivePromotionHistorySpec {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionHistorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionHistoryStatus) DeepCopyInto(out *ActivePromotionHistoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionHistoryStatus.
func (in *ActivePromotionHistoryStatus) DeepCopy() *ActivePromotionHistoryStatus {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionHistoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionList) DeepCopyInto(out *ActivePromotionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActivePromotion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionList.
func (in *ActivePromotionList) DeepCopy() *ActivePromotionList {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActivePromotionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionSpec) DeepCopyInto(out *ActivePromotionSpec) {
	*out = *in
	if in.TearDownDuration != nil {
		in, out := &in.TearDownDuration, &out.TearDownDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionSpec.
func (in *ActivePromotionSpec) DeepCopy() *ActivePromotionSpec {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivePromotionStatus) DeepCopyInto(out *ActivePromotionStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.DestroyedTime != nil {
		in, out := &in.DestroyedTime, &out.DestroyedTime
		*out = (*in).DeepCopy()
	}
	if in.ActiveComponents != nil {
		in, out := &in.ActiveComponents, &out.ActiveComponents
		*out = make(map[string]StableComponent, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.OutdatedComponents != nil {
		in, out := &in.OutdatedComponents, &out.OutdatedComponents
		*out = make(map[string]OutdatedComponent, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.PreActiveQueue.DeepCopyInto(&out.PreActiveQueue)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ActivePromotionCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivePromotionStatus.
func (in *ActivePromotionStatus) DeepCopy() *ActivePromotionStatus {
	if in == nil {
		return nil
	}
	out := new(ActivePromotionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ByNoOfOrder) DeepCopyInto(out *ByNoOfOrder) {
	{
		in := &in
		*out = make(ByNoOfOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByNoOfOrder.
func (in ByNoOfOrder) DeepCopy() ByNoOfOrder {
	if in == nil {
		return nil
	}
	out := new(ByNoOfOrder)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ChartValuesURLs) DeepCopyInto(out *ChartValuesURLs) {
	{
		in := &in
		*out = make(ChartValuesURLs, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartValuesURLs.
func (in ChartValuesURLs) DeepCopy() ChartValuesURLs {
	if in == nil {
		return nil
	}
	out := new(ChartValuesURLs)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandAndArgs) DeepCopyInto(out *CommandAndArgs) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandAndArgs.
func (in *CommandAndArgs) DeepCopy() *CommandAndArgs {
	if in == nil {
		return nil
	}
	out := new(CommandAndArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
	out.Chart = in.Chart
	out.Image = in.Image
	in.Values.DeepCopyInto(&out.Values)
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(UpdatingSource)
		**out = **in
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]*Component, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Component)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentChart) DeepCopyInto(out *ComponentChart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentChart.
func (in *ComponentChart) DeepCopy() *ComponentChart {
	if in == nil {
		return nil
	}
	out := new(ComponentChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentImage) DeepCopyInto(out *ComponentImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentImage.
func (in *ComponentImage) DeepCopy() *ComponentImage {
	if in == nil {
		return nil
	}
	out := new(ComponentImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigActivePromotion) DeepCopyInto(out *ConfigActivePromotion) {
	*out = *in
	out.Timeout = in.Timeout
	out.DemotionTimeout = in.DemotionTimeout
	out.RollbackTimeout = in.RollbackTimeout
	out.TearDownDuration = in.TearDownDuration
	if in.OutdatedNotification != nil {
		in, out := &in.OutdatedNotification, &out.OutdatedNotification
		*out = new(OutdatedNotification)
		**out = **in
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(ConfigDeploy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigActivePromotion.
func (in *ConfigActivePromotion) DeepCopy() *ConfigActivePromotion {
	if in == nil {
		return nil
	}
	out := new(ConfigActivePromotion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigComponentUpgrade) DeepCopyInto(out *ConfigComponentUpgrade) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigComponentUpgrade.
func (in *ConfigComponentUpgrade) DeepCopy() *ConfigComponentUpgrade {
	if in == nil {
		return nil
	}
	out := new(ConfigComponentUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDeploy) DeepCopyInto(out *ConfigDeploy) {
	*out = *in
	out.Timeout = in.Timeout
	out.ComponentCleanupTimeout = in.ComponentCleanupTimeout
	if in.Engine != nil {
		in, out := &in.Engine, &out.Engine
		*out = new(string)
		**out = **in
	}
	if in.TestRunner != nil {
		in, out := &in.TestRunner, &out.TestRunner
		*out = new(ConfigTestRunner)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDeploy.
func (in *ConfigDeploy) DeepCopy() *ConfigDeploy {
	if in == nil {
		return nil
	}
	out := new(ConfigDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigList) DeepCopyInto(out *ConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigList.
func (in *ConfigList) DeepCopy() *ConfigList {
	if in == nil {
		return nil
	}
	out := new(ConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigReporter) DeepCopyInto(out *ConfigReporter) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = make([]ReportOption, len(*in))
		copy(*out, *in)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(Slack)
		(*in).DeepCopyInto(*out)
	}
	if in.MSTeams != nil {
		in, out := &in.MSTeams, &out.MSTeams
		*out = new(MSTeams)
		(*in).DeepCopyInto(*out)
	}
	if in.Rest != nil {
		in, out := &in.Rest, &out.Rest
		*out = new(Rest)
		(*in).DeepCopyInto(*out)
	}
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = new(Shell)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReporter.
func (in *ConfigReporter) DeepCopy() *ConfigReporter {
	if in == nil {
		return nil
	}
	out := new(ConfigReporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]*Component, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Component)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Staging != nil {
		in, out := &in.Staging, &out.Staging
		*out = new(ConfigStaging)
		(*in).DeepCopyInto(*out)
	}
	if in.ActivePromotion != nil {
		in, out := &in.ActivePromotion, &out.ActivePromotion
		*out = new(ConfigActivePromotion)
		(*in).DeepCopyInto(*out)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[EnvType]ChartValuesURLs, len(*in))
		for key, val := range *in {
			var outVal map[string][]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(ChartValuesURLs, len(*in))
				for key, val := range *in {
					var outVal []string
					if val == nil {
						(*out)[key] = nil
					} else {
						in, out := &val, &outVal
						*out = make([]string, len(*in))
						copy(*out, *in)
					}
					(*out)[key] = outVal
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Reporter != nil {
		in, out := &in.Reporter, &out.Reporter
		*out = new(ConfigReporter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStaging) DeepCopyInto(out *ConfigStaging) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(ConfigDeploy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStaging.
func (in *ConfigStaging) DeepCopy() *ConfigStaging {
	if in == nil {
		return nil
	}
	out := new(ConfigStaging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStatus) DeepCopyInto(out *ConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStatus.
func (in *ConfigStatus) DeepCopy() *ConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTeamcity) DeepCopyInto(out *ConfigTeamcity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTeamcity.
func (in *ConfigTeamcity) DeepCopy() *ConfigTeamcity {
	if in == nil {
		return nil
	}
	out := new(ConfigTeamcity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTestMock) DeepCopyInto(out *ConfigTestMock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTestMock.
func (in *ConfigTestMock) DeepCopy() *ConfigTestMock {
	if in == nil {
		return nil
	}
	out := new(ConfigTestMock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTestRunner) DeepCopyInto(out *ConfigTestRunner) {
	*out = *in
	out.Timeout = in.Timeout
	out.PollingTime = in.PollingTime
	if in.Teamcity != nil {
		in, out := &in.Teamcity, &out.Teamcity
		*out = new(ConfigTeamcity)
		**out = **in
	}
	if in.TestMock != nil {
		in, out := &in.TestMock, &out.TestMock
		*out = new(ConfigTestMock)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTestRunner.
func (in *ConfigTestRunner) DeepCopy() *ConfigTestRunner {
	if in == nil {
		return nil
	}
	out := new(ConfigTestRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Credential) DeepCopyInto(out *Credential) {
	*out = *in
	if in.Teamcity != nil {
		in, out := &in.Teamcity, &out.Teamcity
		*out = new(UsernamePasswordCredential)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Credential.
func (in *Credential) DeepCopy() *Credential {
	if in == nil {
		return nil
	}
	out := new(Credential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredComponent) DeepCopyInto(out *DesiredComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredComponent.
func (in *DesiredComponent) DeepCopy() *DesiredComponent {
	if in == nil {
		return nil
	}
	out := new(DesiredComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesiredComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredComponentList) DeepCopyInto(out *DesiredComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesiredComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredComponentList.
func (in *DesiredComponentList) DeepCopy() *DesiredComponentList {
	if in == nil {
		return nil
	}
	out := new(DesiredComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesiredComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredComponentSpec) DeepCopyInto(out *DesiredComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredComponentSpec.
func (in *DesiredComponentSpec) DeepCopy() *DesiredComponentSpec {
	if in == nil {
		return nil
	}
	out := new(DesiredComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredComponentStatus) DeepCopyInto(out *DesiredComponentStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredComponentStatus.
func (in *DesiredComponentStatus) DeepCopy() *DesiredComponentStatus {
	if in == nil {
		return nil
	}
	out := new(DesiredComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesiredImageTime) DeepCopyInto(out *DesiredImageTime) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(Image)
		**out = **in
	}
	in.CreatedTime.DeepCopyInto(&out.CreatedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesiredImageTime.
func (in *DesiredImageTime) DeepCopy() *DesiredImageTime {
	if in == nil {
		return nil
	}
	out := new(DesiredImageTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSTeams) DeepCopyInto(out *MSTeams) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]MSTeamsGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComponentUpgrade != nil {
		in, out := &in.ComponentUpgrade, &out.ComponentUpgrade
		*out = new(ConfigComponentUpgrade)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSTeams.
func (in *MSTeams) DeepCopy() *MSTeams {
	if in == nil {
		return nil
	}
	out := new(MSTeams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSTeamsGroup) DeepCopyInto(out *MSTeamsGroup) {
	*out = *in
	if in.ChannelNameOrIDs != nil {
		in, out := &in.ChannelNameOrIDs, &out.ChannelNameOrIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSTeamsGroup.
func (in *MSTeamsGroup) DeepCopy() *MSTeamsGroup {
	if in == nil {
		return nil
	}
	out := new(MSTeamsGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutdatedComponent) DeepCopyInto(out *OutdatedComponent) {
	*out = *in
	if in.CurrentImage != nil {
		in, out := &in.CurrentImage, &out.CurrentImage
		*out = new(Image)
		**out = **in
	}
	if in.DesiredImage != nil {
		in, out := &in.DesiredImage, &out.DesiredImage
		*out = new(Image)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutdatedComponent.
func (in *OutdatedComponent) DeepCopy() *OutdatedComponent {
	if in == nil {
		return nil
	}
	out := new(OutdatedComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutdatedNotification) DeepCopyInto(out *OutdatedNotification) {
	*out = *in
	out.ExceedDuration = in.ExceedDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutdatedNotification.
func (in *OutdatedNotification) DeepCopy() *OutdatedNotification {
	if in == nil {
		return nil
	}
	out := new(OutdatedNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Queue) DeepCopyInto(out *Queue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Queue.
func (in *Queue) DeepCopy() *Queue {
	if in == nil {
		return nil
	}
	out := new(Queue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Queue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueCondition) DeepCopyInto(out *QueueCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueCondition.
func (in *QueueCondition) DeepCopy() *QueueCondition {
	if in == nil {
		return nil
	}
	out := new(QueueCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueHistory) DeepCopyInto(out *QueueHistory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueHistory.
func (in *QueueHistory) DeepCopy() *QueueHistory {
	if in == nil {
		return nil
	}
	out := new(QueueHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueHistory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in QueueHistoryByCreatedTimeDESC) DeepCopyInto(out *QueueHistoryByCreatedTimeDESC) {
	{
		in := &in
		*out = make(QueueHistoryByCreatedTimeDESC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueHistoryByCreatedTimeDESC.
func (in QueueHistoryByCreatedTimeDESC) DeepCopy() QueueHistoryByCreatedTimeDESC {
	if in == nil {
		return nil
	}
	out := new(QueueHistoryByCreatedTimeDESC)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueHistoryList) DeepCopyInto(out *QueueHistoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueueHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueHistoryList.
func (in *QueueHistoryList) DeepCopy() *QueueHistoryList {
	if in == nil {
		return nil
	}
	out := new(QueueHistoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueHistoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueHistorySpec) DeepCopyInto(out *QueueHistorySpec) {
	*out = *in
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(Queue)
		(*in).DeepCopyInto(*out)
	}
	in.AppliedValues.DeepCopyInto(&out.AppliedValues)
	if in.StableComponents != nil {
		in, out := &in.StableComponents, &out.StableComponents
		*out = make([]StableComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueHistorySpec.
func (in *QueueHistorySpec) DeepCopy() *QueueHistorySpec {
	if in == nil {
		return nil
	}
	out := new(QueueHistorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueHistoryStatus) DeepCopyInto(out *QueueHistoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueHistoryStatus.
func (in *QueueHistoryStatus) DeepCopy() *QueueHistoryStatus {
	if in == nil {
		return nil
	}
	out := new(QueueHistoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueList) DeepCopyInto(out *QueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Queue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueList.
func (in *QueueList) DeepCopy() *QueueList {
	if in == nil {
		return nil
	}
	out := new(QueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
	if in.NextProcessAt != nil {
		in, out := &in.NextProcessAt, &out.NextProcessAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSpec.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueStatus) DeepCopyInto(out *QueueStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.NextProcessAt != nil {
		in, out := &in.NextProcessAt, &out.NextProcessAt
		*out = (*in).DeepCopy()
	}
	if in.StartDeployTime != nil {
		in, out := &in.StartDeployTime, &out.StartDeployTime
		*out = (*in).DeepCopy()
	}
	if in.StartTestingTime != nil {
		in, out := &in.StartTestingTime, &out.StartTestingTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]QueueCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TestRunner = in.TestRunner
	if in.ImageMissingList != nil {
		in, out := &in.ImageMissingList, &out.ImageMissingList
		*out = make([]Image, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatus.
func (in *QueueStatus) DeepCopy() *QueueStatus {
	if in == nil {
		return nil
	}
	out := new(QueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportOption) DeepCopyInto(out *ReportOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportOption.
func (in *ReportOption) DeepCopy() *ReportOption {
	if in == nil {
		return nil
	}
	out := new(ReportOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rest) DeepCopyInto(out *Rest) {
	*out = *in
	if in.ComponentUpgrade != nil {
		in, out := &in.ComponentUpgrade, &out.ComponentUpgrade
		*out = new(RestObject)
		(*in).DeepCopyInto(*out)
	}
	if in.ActivePromotion != nil {
		in, out := &in.ActivePromotion, &out.ActivePromotion
		*out = new(RestObject)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageMissing != nil {
		in, out := &in.ImageMissing, &out.ImageMissing
		*out = new(RestObject)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rest.
func (in *Rest) DeepCopy() *Rest {
	if in == nil {
		return nil
	}
	out := new(Rest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestObject) DeepCopyInto(out *RestObject) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*Endpoint, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Endpoint)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestObject.
func (in *RestObject) DeepCopy() *RestObject {
	if in == nil {
		return nil
	}
	out := new(RestObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Shell) DeepCopyInto(out *Shell) {
	*out = *in
	if in.ComponentUpgrade != nil {
		in, out := &in.ComponentUpgrade, &out.ComponentUpgrade
		*out = new(CommandAndArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ActivePromotion != nil {
		in, out := &in.ActivePromotion, &out.ActivePromotion
		*out = new(CommandAndArgs)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageMissing != nil {
		in, out := &in.ImageMissing, &out.ImageMissing
		*out = new(CommandAndArgs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Shell.
func (in *Shell) DeepCopy() *Shell {
	if in == nil {
		return nil
	}
	out := new(Shell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Slack) DeepCopyInto(out *Slack) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComponentUpgrade != nil {
		in, out := &in.ComponentUpgrade, &out.ComponentUpgrade
		*out = new(ConfigComponentUpgrade)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Slack.
func (in *Slack) DeepCopy() *Slack {
	if in == nil {
		return nil
	}
	out := new(Slack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StableComponent) DeepCopyInto(out *StableComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StableComponent.
func (in *StableComponent) DeepCopy() *StableComponent {
	if in == nil {
		return nil
	}
	out := new(StableComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StableComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StableComponentList) DeepCopyInto(out *StableComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StableComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StableComponentList.
func (in *StableComponentList) DeepCopy() *StableComponentList {
	if in == nil {
		return nil
	}
	out := new(StableComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StableComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StableComponentSpec) DeepCopyInto(out *StableComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StableComponentSpec.
func (in *StableComponentSpec) DeepCopy() *StableComponentSpec {
	if in == nil {
		return nil
	}
	out := new(StableComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StableComponentStatus) DeepCopyInto(out *StableComponentStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StableComponentStatus.
func (in *StableComponentStatus) DeepCopy() *StableComponentStatus {
	if in == nil {
		return nil
	}
	out := new(StableComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StagingCtrl) DeepCopyInto(out *StagingCtrl) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StagingCtrl.
func (in *StagingCtrl) DeepCopy() *StagingCtrl {
	if in == nil {
		return nil
	}
	out := new(StagingCtrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamCondition) DeepCopyInto(out *TeamCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamCondition.
func (in *TeamCondition) DeepCopy() *TeamCondition {
	if in == nil {
		return nil
	}
	out := new(TeamCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamDesiredImageTime) DeepCopyInto(out *TeamDesiredImageTime) {
	*out = *in
	in.ImageTime.DeepCopyInto(&out.ImageTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamDesiredImageTime.
func (in *TeamDesiredImageTime) DeepCopy() *TeamDesiredImageTime {
	if in == nil {
		return nil
	}
	out := new(TeamDesiredImageTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TeamDesiredImageTimeList) DeepCopyInto(out *TeamDesiredImageTimeList) {
	{
		in := &in
		*out = make(TeamDesiredImageTimeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamDesiredImageTimeList.
func (in TeamDesiredImageTimeList) DeepCopy() TeamDesiredImageTimeList {
	if in == nil {
		return nil
	}
	out := new(TeamDesiredImageTimeList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamNamespace) DeepCopyInto(out *TeamNamespace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamNamespace.
func (in *TeamNamespace) DeepCopy() *TeamNamespace {
	if in == nil {
		return nil
	}
	out := new(TeamNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.StagingCtrl != nil {
		in, out := &in.StagingCtrl, &out.StagingCtrl
		*out = new(StagingCtrl)
		(*in).DeepCopyInto(*out)
	}
	in.Credential.DeepCopyInto(&out.Credential)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	out.Namespace = in.Namespace
	if in.StableComponents != nil {
		in, out := &in.StableComponents, &out.StableComponents
		*out = make(map[string]StableComponent, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ActiveComponents != nil {
		in, out := &in.ActiveComponents, &out.ActiveComponents
		*out = make(map[string]StableComponent, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TeamCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DesiredComponentImageCreatedTime != nil {
		in, out := &in.DesiredComponentImageCreatedTime, &out.DesiredComponentImageCreatedTime
		*out = make(map[string]map[string]DesiredImageTime, len(*in))
		for key, val := range *in {
			var outVal map[string]DesiredImageTime
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(map[string]DesiredImageTime, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Teamcity) DeepCopyInto(out *Teamcity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Teamcity.
func (in *Teamcity) DeepCopy() *Teamcity {
	if in == nil {
		return nil
	}
	out := new(Teamcity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestRunner) DeepCopyInto(out *TestRunner) {
	*out = *in
	out.Teamcity = in.Teamcity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestRunner.
func (in *TestRunner) DeepCopy() *TestRunner {
	if in == nil {
		return nil
	}
	out := new(TestRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenCredential) DeepCopyInto(out *TokenCredential) {
	*out = *in
	if in.TokenRef != nil {
		in, out := &in.TokenRef, &out.TokenRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenCredential.
func (in *TokenCredential) DeepCopy() *TokenCredential {
	if in == nil {
		return nil
	}
	out := new(TokenCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsernamePasswordCredential) DeepCopyInto(out *UsernamePasswordCredential) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsernamePasswordCredential.
func (in *UsernamePasswordCredential) DeepCopy() *UsernamePasswordCredential {
	if in == nil {
		return nil
	}
	out := new(UsernamePasswordCredential)
	in.DeepCopyInto(out)
	return out
}
