apiVersion: v1
kind: Secret
metadata:
  # the secret name must match with credentials defining in Team.yaml
  # name must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  name: <your_secret_name>
data:
  tcUsername: <base64_teamcity_username>
  tcPassword: <base64_teamcity_token>
  gitToken: <base64_git_token>