# Default values for samsahai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/samsahai/samsahai
  tag: latest
  pullPolicy: Always

imagePullSecrets: []

replicaCount: 1

debug: false

nameOverride: ""

fullnameOverride: "samsahai"

extraEnvs: {}

configs:
  S2H_CONFIG_PATH: "samsahai.yaml"
  S2H_SERVICE_NAME: '{{ include "samsahai.fullname" . }}'

fileConfigs:
  s2hImage: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
  clusterDomain: "cluster.local"
  githubURL: "https://github.com"
  gitlabURL: "https://gitlab.com"

  # cpu/memory of cronjobs for sending new component webhook
  checkerResources:
    cpu: 100m
    memory: 125Mi

  # required minimum cpu/memory of resources quota
  # which will be used for mock deployment engine.
  # It will be activated for only the Team that have resources quota defined.
  initialResourcesQuota:
    cpu: '3'
    memory: 3Gi

  # pullRequest global config
  pullRequest:
    # how many concurrences of pull request queue running?
    queueConcurrences: 2

    # how many times the pull request component should be tested?
    maxVerificationRetryCounts: 0

    # how many times the image version should be checked ?
    maxTriggerRetryCounts: 30

    # polling time to verify the image version
    triggerPollingTime: 5m

    # what is the maximum pull request queue histories in days to store?
    maxHistoryDays: 7

  # activePromotion global config
  activePromotion:
    # how many active promotions can run in parallel?
    concurrences: 3

    # how many times the active promotion should be processed?
    maxRetry: 0

    # how long for active promotion flow?
    timeout: "30m"

    # how many max histories of active promotion?
    maxHistories: 10

    # how long before destroying previous active namespace?
    # this is for successful active promotion
    teardownDuration: "10m"

    # how long for demotion flow?
    # this is for successful active promotion
    # demotion timeout should be less than rollback timeout
    demotionTimeout: "3m"

    # how long for rollback flow when promotion flow has problem?
    # this is for failed active promotion
    rollbackTimeout: "5m"

    # would you like to auto promote active namespace when team is created?
    # if you do not set this flag, the default value is true
    promoteOnTeamCreation: true

  # environment variables for staging controller
  stagingEnvs:
    NO_PROXY: '.{{ .Release.Namespace }}'

    # how many days of queue histories will be kept?
    QUEUE_MAX_HISTORY_DAYS: "7"

# the value in this field should be base64 encoder
credentials: null
#  # this is the token for GRPC communication between samsahai and staging controller
#  S2H_AUTH_TOKEN: "base64_auth_token"
#  SLACK_TOKEN: "base64_slack_token"

service:
  type: NodePort
  http: 8080

exporter:
  enabled: false
  port: 8081

ingress:
  enabled: false
  annotations: {}
  #    kubernetes.io/ingress.class: nginx
  #    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

## Enable RBAC as per https://github.com/kubernetes/ingress/tree/master/examples/rbac/nginx and https://github.com/kubernetes/ingress/issues/266
rbac:
  pspEnabled: false
  pspUseAppArmor: false