// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-05-14 23:01:50.638211 +0700 +07 m=+0.131522713

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activepromotions": {
            "get": {
                "description": "get current active promotions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "get current active promotions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.activePromotion"
                        }
                    },
                    "500": {
                        "description": "cannot get activepromotions",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Endpoint for server health check",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.healthCheckJSON"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "description": "Returns a list of teams that currently running on Samsahai.",
                "tags": [
                    "GET"
                ],
                "summary": "Get Teams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.teamsJSON"
                        }
                    }
                }
            }
        },
        "/teams/{team}": {
            "get": {
                "description": "Returns team information. (namespaces, connections)",
                "tags": [
                    "GET"
                ],
                "summary": "Get Team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.teamJSON"
                        }
                    },
                    "404": {
                        "description": "Team not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/teams/{team}/activepromotions": {
            "get": {
                "description": "get active promotions by team name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "get active promotions by team name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.teamActivePromotion"
                        }
                    },
                    "404": {
                        "description": "team {team} not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "cannot get activepromotion/activepromotion histories of team {team}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teams/{team}/activepromotions/histories": {
            "get": {
                "description": "get active promotion histories by team name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "get active promotion histories by team name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.activePromotionHistories"
                        }
                    },
                    "400": {
                        "description": "team should not be empty",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "cannot get activepromotion histories of team {team}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teams/{team}/activepromotions/histories/{history}": {
            "get": {
                "description": "get active promotion history by team and history name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "get active promotion history by team and history name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Active promotion history name",
                        "name": "history",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "team/history should not be empty",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "activepromotion history {history} of team {team} not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "cannot get activepromotion history {history} of team {team}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teams/{team}/activepromotions/histories/{history}/log": {
            "get": {
                "description": "Returns zip log file of the active promotion history",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "Get zip log of active promotion history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Active promotion history name",
                        "name": "history",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "team/history should not be empty",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "activepromotion history {history} of team {team} not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "cannot get activepromotion history {history} of team {team}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teams/{team}/components": {
            "get": {
                "description": "Returns list of components of team",
                "tags": [
                    "GET"
                ],
                "summary": "Get Team Component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.teamComponentsJSON"
                        }
                    },
                    "404": {
                        "description": "Team not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/teams/{team}/components/{component}/values": {
            "get": {
                "description": "get team stable component values",
                "tags": [
                    "GET"
                ],
                "summary": "get team stable component values",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Component name",
                        "name": "component",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "application/json",
                            "application/x-yaml"
                        ],
                        "type": "string",
                        "description": "Accept",
                        "name": "accept",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Component not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/teams/{team}/config": {
            "get": {
                "description": "get team configuration",
                "tags": [
                    "GET"
                ],
                "summary": "get team configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "application/json",
                            "application/x-yaml"
                        ],
                        "type": "string",
                        "description": "Accept",
                        "name": "accept",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Team not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/teams/{team}/queue": {
            "get": {
                "description": "Returns queue information of new component upgrading flow.",
                "tags": [
                    "GET"
                ],
                "summary": "Get Team's Queues",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.teamQueueJSON"
                        }
                    },
                    "404": {
                        "description": "Team not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/teams/{team}/queue/histories/{queue}": {
            "get": {
                "description": "Return queue history of team by id",
                "tags": [
                    "GET"
                ],
                "summary": "Get Team Queue History",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Queue history name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.QueueHistory"
                        }
                    },
                    "404": {
                        "description": "Queue history not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/teams/{team}/queue/histories/{queue}/log": {
            "get": {
                "description": "Returns zip log file of the queue history",
                "tags": [
                    "GET"
                ],
                "summary": "Get Team Queue History Log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team name",
                        "name": "team",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Queue history name",
                        "name": "queue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.QueueHistory"
                        }
                    },
                    "404": {
                        "description": "Queue history not found",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Get service version information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "Service Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webhook.versionJSON"
                        }
                    }
                }
            }
        },
        "/webhook/component": {
            "post": {
                "description": "Endpoint for manually triggering new component update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "POST"
                ],
                "summary": "Webhook New Component",
                "parameters": [
                    {
                        "description": "New Component",
                        "name": "newComponentEventJSON",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/webhook.newComponentEventJSON"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "$ref": "#/definitions/webhook.errResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.CommandAndArgs": {
            "type": "object",
            "properties": {
                "args": {
                    "description": "+optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1.Component": {
            "type": "object",
            "properties": {
                "chart": {
                    "type": "object",
                    "$ref": "#/definitions/v1.ComponentChart"
                },
                "dependencies": {
                    "description": "+optional",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Dependency"
                    }
                },
                "image": {
                    "type": "object",
                    "$ref": "#/definitions/v1.ComponentImage"
                },
                "name": {
                    "type": "string"
                },
                "parent": {
                    "description": "+optional",
                    "type": "string"
                },
                "source": {
                    "description": "+optional",
                    "type": "string"
                },
                "values": {
                    "description": "+optional\n+kubebuilder:pruning:PreserveUnknownFields",
                    "type": "object",
                    "$ref": "#/definitions/v1.ComponentValues"
                }
            }
        },
        "v1.ComponentChart": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                },
                "version": {
                    "description": "+optional",
                    "type": "string"
                }
            }
        },
        "v1.ComponentImage": {
            "type": "object",
            "properties": {
                "pattern": {
                    "description": "+optional",
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                },
                "tag": {
                    "description": "+optional",
                    "type": "string"
                }
            }
        },
        "v1.ComponentValues": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "v1.ConfigActivePromotion": {
            "type": "object",
            "properties": {
                "demotionTimeout": {
                    "description": "DemotionTimeout defines maximum duration for doing active demotion\n+optional",
                    "type": "string"
                },
                "deployment": {
                    "description": "Deployment represents configuration about deploy",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigDeploy"
                },
                "maxHistories": {
                    "description": "MaxHistories defines maximum length of ActivePromotionHistory stored per team\n+optional",
                    "type": "integer"
                },
                "outdatedNotification": {
                    "description": "OutdatedNotification defines a configuration of outdated notification\n+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.OutdatedNotification"
                },
                "rollbackTimeout": {
                    "description": "RollbackTimeout defines maximum duration for rolling back active promotion\n+optional",
                    "type": "string"
                },
                "tearDownDuration": {
                    "description": "TearDownDuration defines duration before teardown the previous active namespace\n+optional",
                    "type": "string"
                },
                "timeout": {
                    "description": "Timeout defines maximum duration for doing active promotion\n+optional",
                    "type": "string"
                }
            }
        },
        "v1.ConfigComponentUpgrade": {
            "type": "object",
            "properties": {
                "criteria": {
                    "description": "+optional",
                    "type": "string"
                },
                "interval": {
                    "description": "+optional",
                    "type": "string"
                }
            }
        },
        "v1.ConfigDeploy": {
            "type": "object",
            "properties": {
                "componentCleanupTimeout": {
                    "description": "ComponentCleanupTimeout defines timeout duration of component cleaning up\n+optional",
                    "type": "string"
                },
                "engine": {
                    "description": "Engine defines method of deploying\n\nmock - for test only, always return success\n\nflux-helm - create HelmRelease for Helm Operator from Flux\n+optional",
                    "type": "string"
                },
                "testRunner": {
                    "description": "TestRunner represents configuration about test\n+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigTestRunner"
                },
                "timeout": {
                    "description": "Timeout defines maximum duration for deploying environment\n+optional",
                    "type": "string"
                }
            }
        },
        "v1.ConfigReporter": {
            "type": "object",
            "properties": {
                "cmd": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.Shell"
                },
                "msTeams": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.MSTeams"
                },
                "optionals": {
                    "description": "+optional",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ReportOption"
                    }
                },
                "reportMock": {
                    "description": "+optional",
                    "type": "boolean"
                },
                "rest": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.Rest"
                },
                "slack": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.Slack"
                }
            }
        },
        "v1.ConfigSpec": {
            "type": "object",
            "properties": {
                "activePromotion": {
                    "description": "ActivePromotion represents configuration about active promotion\n+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigActivePromotion"
                },
                "components": {
                    "description": "Components represents all components that are managed",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Component"
                    }
                },
                "envs": {
                    "description": "Envs represents urls of values file per environments\nordering by less priority to high priority\n+optional",
                    "type": "object"
                },
                "report": {
                    "description": "Reporter represents configuration about reporter\n+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigReporter"
                },
                "staging": {
                    "description": "Staging represents configuration about staging",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigStaging"
                }
            }
        },
        "v1.ConfigStaging": {
            "type": "object",
            "properties": {
                "deployment": {
                    "description": "Deployment represents configuration about deploy",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigDeploy"
                },
                "maxHistoryDays": {
                    "description": "MaxHistoryDays defines maximum days of QueueHistory stored\n+optional",
                    "type": "integer"
                },
                "maxRetry": {
                    "description": "MaxRetry defines max retry counts of component upgrade\n+optional",
                    "type": "integer"
                }
            }
        },
        "v1.ConfigTeamcity": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "buildTypeID": {
                    "type": "string"
                }
            }
        },
        "v1.ConfigTestMock": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "v1.ConfigTestRunner": {
            "type": "object",
            "properties": {
                "pollingTime": {
                    "description": "+optional",
                    "type": "string"
                },
                "teamcity": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigTeamcity"
                },
                "testMock": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigTestMock"
                },
                "timeout": {
                    "description": "+optional",
                    "type": "string"
                }
            }
        },
        "v1.Dependency": {
            "type": "object",
            "properties": {
                "chart": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ComponentChart"
                },
                "image": {
                    "type": "object",
                    "$ref": "#/definitions/v1.ComponentImage"
                },
                "name": {
                    "type": "string"
                },
                "parent": {
                    "description": "+optional",
                    "type": "string"
                },
                "source": {
                    "description": "+optional",
                    "type": "string"
                },
                "values": {
                    "description": "+optional\n+kubebuilder:pruning:PreserveUnknownFields",
                    "type": "object",
                    "$ref": "#/definitions/v1.ComponentValues"
                }
            }
        },
        "v1.Endpoint": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "v1.Image": {
            "type": "object",
            "properties": {
                "repository": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "v1.MSTeams": {
            "type": "object",
            "properties": {
                "componentUpgrade": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigComponentUpgrade"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.MSTeamsGroup"
                    }
                }
            }
        },
        "v1.MSTeamsGroup": {
            "type": "object",
            "properties": {
                "channelNameOrIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "groupNameOrID": {
                    "type": "string"
                }
            }
        },
        "v1.OutdatedNotification": {
            "type": "object",
            "properties": {
                "exceedDuration": {
                    "description": "+optional",
                    "type": "string"
                },
                "excludeWeekendCalculation": {
                    "description": "+optional",
                    "type": "boolean"
                }
            }
        },
        "v1.Queue": {
            "type": "object",
            "properties": {
                "spec": {
                    "type": "object",
                    "$ref": "#/definitions/v1.QueueSpec"
                },
                "status": {
                    "type": "object",
                    "$ref": "#/definitions/v1.QueueStatus"
                }
            }
        },
        "v1.QueueCondition": {
            "type": "object",
            "properties": {
                "lastTransitionTime": {
                    "description": "+optional",
                    "type": "string"
                },
                "message": {
                    "description": "+optional",
                    "type": "string"
                },
                "reason": {
                    "description": "+optional",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1.QueueHistory": {
            "type": "object",
            "properties": {
                "spec": {
                    "type": "object",
                    "$ref": "#/definitions/v1.QueueHistorySpec"
                },
                "status": {
                    "type": "object",
                    "$ref": "#/definitions/v1.QueueHistoryStatus"
                }
            }
        },
        "v1.QueueHistorySpec": {
            "type": "object",
            "properties": {
                "appliedValues": {
                    "type": "object",
                    "$ref": "#/definitions/v1.Values"
                },
                "createdAt": {
                    "type": "string"
                },
                "isDeploySuccess": {
                    "type": "boolean"
                },
                "isReverify": {
                    "type": "boolean"
                },
                "isTestSuccess": {
                    "type": "boolean"
                },
                "queue": {
                    "type": "object",
                    "$ref": "#/definitions/v1.Queue"
                },
                "stableComponents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.StableComponent"
                    }
                }
            }
        },
        "v1.QueueHistoryStatus": {
            "type": "object"
        },
        "v1.QueueSpec": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name represents Component name",
                    "type": "string"
                },
                "nextProcessAt": {
                    "description": "NextProcessAt represents time to wait for process this queue",
                    "type": "string"
                },
                "noOfOrder": {
                    "description": "NoOfOrder defines the position in queue\nlower is will be picked first",
                    "type": "integer"
                },
                "noOfRetry": {
                    "description": "NoOfRetry defines how many times this component has been tested\n+optional",
                    "type": "integer"
                },
                "repository": {
                    "description": "Repository represents Docker image repository",
                    "type": "string"
                },
                "teamName": {
                    "description": "TeamName represents team owner of the queue",
                    "type": "string"
                },
                "type": {
                    "description": "Type represents how we will process this queue",
                    "type": "string"
                },
                "version": {
                    "description": "Version represents Docker image tag version",
                    "type": "string"
                }
            }
        },
        "v1.QueueStatus": {
            "type": "object",
            "properties": {
                "conditions": {
                    "description": "Conditions contains observations of the resource's state e.g.,\nQueue deployed, being tested\n+optional\n+patchMergeKey=type\n+patchStrategy=merge",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.QueueCondition"
                    }
                },
                "createdAt": {
                    "description": "CreatedAt represents time when the component has been added to queue",
                    "type": "string"
                },
                "deployEngine": {
                    "description": "DeployEngine represents engine using during installation",
                    "type": "string"
                },
                "imageMissingList": {
                    "description": "ImageMissingList defines image missing list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Image"
                    }
                },
                "kubeZipLog": {
                    "description": "KubeZipLog defines log of k8s resources during deployment in base64 zip format",
                    "type": "string"
                },
                "nextProcessAt": {
                    "description": "NextProcessAt represents time to wait for process this queue",
                    "type": "string"
                },
                "noOfProcessed": {
                    "description": "NoOfProcessed represents how many time that this queue had been processed",
                    "type": "integer"
                },
                "queueHistoryName": {
                    "description": "QueueHistoryName defines name of history of this queue",
                    "type": "string"
                },
                "releaseName": {
                    "description": "ReleaseName defines name of helmrelease",
                    "type": "string"
                },
                "startDeployTime": {
                    "description": "StartDeployTime represents the time when this queue start deploying",
                    "type": "string"
                },
                "startTestingTime": {
                    "description": "StartTestingTime represents the time when this queue start testing",
                    "type": "string"
                },
                "state": {
                    "description": "State represents current status of this queue",
                    "type": "string"
                },
                "testRunners": {
                    "description": "TestRunner defines the test runner",
                    "type": "object",
                    "$ref": "#/definitions/v1.TestRunner"
                },
                "updatedAt": {
                    "description": "UpdatedAt represents time when the component was processed",
                    "type": "string"
                }
            }
        },
        "v1.ReportOption": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "v1.Rest": {
            "type": "object",
            "properties": {
                "activePromotion": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.RestObject"
                },
                "componentUpgrade": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.RestObject"
                },
                "imageMissing": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.RestObject"
                }
            }
        },
        "v1.RestObject": {
            "type": "object",
            "properties": {
                "endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Endpoint"
                    }
                }
            }
        },
        "v1.Shell": {
            "type": "object",
            "properties": {
                "activePromotion": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.CommandAndArgs"
                },
                "componentUpgrade": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.CommandAndArgs"
                },
                "imageMissing": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.CommandAndArgs"
                }
            }
        },
        "v1.Slack": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "componentUpgrade": {
                    "description": "+optional",
                    "type": "object",
                    "$ref": "#/definitions/v1.ConfigComponentUpgrade"
                }
            }
        },
        "v1.StableComponent": {
            "type": "object",
            "properties": {
                "spec": {
                    "type": "object",
                    "$ref": "#/definitions/v1.StableComponentSpec"
                },
                "status": {
                    "type": "object",
                    "$ref": "#/definitions/v1.StableComponentStatus"
                }
            }
        },
        "v1.StableComponentSpec": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name represents Component name",
                    "type": "string"
                },
                "repository": {
                    "description": "Repository represents Docker image repository",
                    "type": "string"
                },
                "updatedBy": {
                    "description": "UpdatedBy represents a person who updated the StableComponent\n+optional",
                    "type": "string"
                },
                "version": {
                    "description": "Version represents Docker image tag version",
                    "type": "string"
                }
            }
        },
        "v1.StableComponentStatus": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "v1.Teamcity": {
            "type": "object",
            "properties": {
                "buildID": {
                    "type": "string"
                },
                "buildTypeID": {
                    "type": "string"
                },
                "buildURL": {
                    "type": "string"
                }
            }
        },
        "v1.TestRunner": {
            "type": "object",
            "properties": {
                "teamcity": {
                    "type": "object",
                    "$ref": "#/definitions/v1.Teamcity"
                }
            }
        },
        "v1.Values": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "webhook.activePromotion": {
            "type": "object",
            "properties": {
                "inQueues": {
                    "description": "+Optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "team1",
                        "team2"
                    ]
                },
                "running": {
                    "description": "+Optional",
                    "type": "string"
                }
            }
        },
        "webhook.activePromotionHistories": {
            "type": "array",
            "items": {}
        },
        "webhook.errResp": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "webhook.healthCheckJSON": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "webhook.newComponentEventJSON": {
            "type": "object",
            "properties": {
                "component": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                }
            }
        },
        "webhook.teamActivePromotion": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "+Optional",
                    "type": "string"
                },
                "historyNames": {
                    "description": "+Optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "team1-20191010-080000",
                        "team1-20191009-080000"
                    ]
                }
            }
        },
        "webhook.teamComponentsJSON": {
            "type": "object",
            "additionalProperties": {}
        },
        "webhook.teamEnvConnections": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "+optional",
                    "type": "object"
                },
                "preActive": {
                    "description": "+optional",
                    "type": "object"
                },
                "staging": {
                    "description": "+optional",
                    "type": "object"
                }
            }
        },
        "webhook.teamJSON": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "object",
                    "$ref": "#/definitions/webhook.teamEnvConnections"
                },
                "spec": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "webhook.teamQueueJSON": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "+Optional",
                    "type": "string"
                },
                "historyNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "noOfQueue": {
                    "description": "+optional",
                    "type": "integer"
                },
                "queues": {
                    "description": "+Optional",
                    "type": "string"
                }
            }
        },
        "webhook.teamsJSON": {
            "type": "object",
            "properties": {
                "teams": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "webhook.versionJSON": {
            "type": "object",
            "properties": {
                "gitCommit": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
