name: Release
on: [push]

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      # BUILD
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.2'

      - uses: actions/checkout@v1
        with:
          path: go/src/github.com/agoda-com/samsahai

      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare ENV
        run: |
          export GOPATH=/home/runner/work/samsahai/go
          echo "::set-env name=GOROOT::$GOROOT"
          echo "::set-env name=GOPATH::$GOPATH"
          echo "::set-env name=INSTALL_DIR::$GOPATH/bin/"

      # RELEASE
      - name: Release
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GIT_PASSWORD }}
          GITHUB_REPO: agoda-com/samsahai
          DOCKER_USER: ${{ secrets.QUAY_DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_DOCKER_TOKEN }}
        run: |
          export INSTALL_DIR="$(pwd)/bin/"

          git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
          git config --global gc.auto 0 || true

          rm -rf tmp
          make auto-release SUDO="sudo "

      - name: Docker logout
        if: always()
        run: |
          make .docker-logout
